name: Run Tests

on:
  push:
    branches:
      - master  # Запускать тесты при пуше в ветку main
  pull_request:
    branches:
      - master  # Запускать тесты при создании пул-реквеста в ветку main

jobs:
  test:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"  # Указываем версию Python

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio

      # Шаг 4: Запускаем тесты
      - name: Run tests
        run: pytest tests/